// Central to Cheung Chau mapped explicitly for Fast vs Ordinary (Cargo) with accurate durations
window.PulseFerry.registerRoute("central-cheung-chau", {
    name: "Central ➔ Cheung Chau",
    category: "islands",
    operator: "Sun Ferry",
    piers: { "CENTRAL": "Central Pier 5", "CC": "Cheung Chau" },
    fares: { 
        adultWeekday: "HK$16.70 (Ord) / $32.90 (Fast)", 
        adultHoliday: "HK$24.80 (Ord) / $47.60 (Fast)" 
    },
    trips: {
        "CENTRAL-CC": [
            { t: "01:30", type: "fast", duration: 35 }, 
            { t: "04:15", type: "fast", duration: 35 },
            { t: "06:10", type: "ordinary", duration: 55, cargo: true }, 
            { t: "07:00", type: "fast", duration: 35 },
            { t: "07:40", type: "ordinary", duration: 55, cargo: true }, 
            { t: "08:00", type: "fast", duration: 35 },
            { t: "08:40", type: "fast", duration: 35 }, 
            { t: "09:00", type: "ordinary", duration: 55, cargo: true },
            { t: "09:45", type: "fast", duration: 35 }, 
            { t: "10:15", type: "ordinary", duration: 55, cargo: true },
            { t: "10:45", type: "fast", duration: 35 }, 
            { t: "11:15", type: "ordinary", duration: 55, cargo: true },
            { t: "11:45", type: "fast", duration: 35 }, 
            { t: "12:15", type: "ordinary", duration: 55, cargo: true },
            { t: "12:45", type: "fast", duration: 35 }, 
            { t: "13:15", type: "ordinary", duration: 55, cargo: true },
            { t: "13:45", type: "fast", duration: 35 }, 
            { t: "14:15", type: "ordinary", duration: 55, cargo: true },
            { t: "14:45", type: "fast", duration: 35 }, 
            { t: "15:15", type: "ordinary", duration: 55, cargo: true },
            { t: "15:45", type: "fast", duration: 35 }, 
            { t: "16:15", type: "ordinary", duration: 55, cargo: true },
            { t: "16:30", type: "fast", duration: 35, weekdayOnly: true },
            { t: "16:45", type: "fast", duration: 35 }, 
            { t: "17:15", type: "ordinary", duration: 55, cargo: true },
            { t: "17:40", type: "fast", duration: 35 }, 
            { t: "18:00", type: "ordinary", duration: 55, cargo: true },
            { t: "18:20", type: "ordinary", duration: 55, cargo: true }, 
            { t: "18:30", type: "fast", duration: 35, weekdayOnly: true },
            { t: "18:45", type: "ordinary", duration: 55, cargo: true }, 
            { t: "19:00", type: "fast", duration: 35 },
            { t: "19:15", type: "fast", duration: 35, weekdayOnly: true }, 
            { t: "19:30", type: "ordinary", duration: 55, cargo: true, weekendOnly: true },
            { t: "19:40", type: "ordinary", duration: 55, cargo: true, weekdayOnly: true }, 
            { t: "20:00", type: "fast", duration: 35 },
            { t: "20:30", type: "ordinary", duration: 55, cargo: true }, 
            { t: "21:00", type: "fast", duration: 35 },
            { t: "21:30", type: "ordinary", duration: 55, cargo: true }, 
            { t: "22:00", type: "fast", duration: 35 },
            { t: "22:30", type: "ordinary", duration: 55, cargo: true }, 
            { t: "23:00", type: "fast", duration: 35 },
            { t: "23:30", type: "ordinary", duration: 55, cargo: true }, 
            { t: "23:45", type: "fast", duration: 35 },
            { t: "00:30", type: "fast", duration: 35 }
        ],
        "CC-CENTRAL": [
            { t: "02:20", type: "fast", duration: 35 }, 
            { t: "05:10", type: "fast", duration: 35 },
            { t: "05:50", type: "ordinary", duration: 55, cargo: true }, 
            { t: "06:20", type: "fast", duration: 35 },
            { t: "06:40", type: "ordinary", duration: 55, cargo: true }, 
            { t: "07:00", type: "fast", duration: 35 },
            { t: "07:15", type: "ordinary", duration: 55, cargo: true }, 
            { t: "07:45", type: "fast", duration: 35 },
            { t: "07:50", type: "ordinary", duration: 55, cargo: true }, 
            { t: "07:55", type: "fast", duration: 35 },
            { t: "08:10", type: "fast", duration: 35 }, 
            { t: "08:20", type: "fast", duration: 35 },
            { t: "08:40", type: "ordinary", duration: 55, cargo: true }, 
            { t: "09:00", type: "fast", duration: 35 },
            { t: "09:30", type: "fast", duration: 35 }, 
            { t: "10:00", type: "ordinary", duration: 55, cargo: true },
            { t: "10:45", type: "fast", duration: 35 }, 
            { t: "11:15", type: "ordinary", duration: 55, cargo: true },
            { t: "11:45", type: "fast", duration: 35 }, 
            { t: "12:15", type: "ordinary", duration: 55, cargo: true },
            { t: "12:45", type: "fast", duration: 35 }, 
            { t: "13:15", type: "ordinary", duration: 55, cargo: true },
            { t: "13:45", type: "fast", duration: 35 }, 
            { t: "14:15", type: "ordinary", duration: 55, cargo: true },
            { t: "14:45", type: "fast", duration: 35 }, 
            { t: "15:15", type: "ordinary", duration: 55, cargo: true },
            { t: "15:45", type: "fast", duration: 35 }, 
            { t: "16:15", type: "ordinary", duration: 55, cargo: true },
            { t: "16:30", type: "fast", duration: 35, weekdayOnly: true },
            { t: "16:45", type: "fast", duration: 35 }, 
            { t: "17:15", type: "ordinary", duration: 55, cargo: true },
            { t: "17:40", type: "fast", duration: 35 }, 
            { t: "18:20", type: "ordinary", duration: 55, cargo: true },
            { t: "19:00", type: "fast", duration: 35 }, 
            { t: "19:30", type: "ordinary", duration: 55, cargo: true },
            { t: "20:00", type: "fast", duration: 35 }, 
            { t: "20:30", type: "ordinary", duration: 55, cargo: true },
            { t: "21:00", type: "fast", duration: 35 }, 
            { t: "21:30", type: "ordinary", duration: 55, cargo: true },
            { t: "22:00", type: "fast", duration: 35 }, 
            { t: "22:30", type: "ordinary", duration: 55, cargo: true },
            { t: "23:00", type: "fast", duration: 35 }, 
            { t: "23:30", type: "ordinary", duration: 55, cargo: true },
            { t: "23:45", type: "fast", duration: 35 }
        ]
    }
});
